[package]
name = "loxide"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ctrlc = { version = "3.2.3", features = ["termination"] }
unicode-segmentation = "1.9.0"